[platformio]
default_envs = demo_display_text

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino


board_build.flash_mode = qio
board_build.flash_size = 16MB

build_flags =
    -DBOARD_HAS_PSRAM

monitor_speed = 115200


; ===== Demo selection =====

[env:demo_display_widgets]
build_src_filter =
    +<demos/display_widgets/>

[env:demo_display_console]
build_src_filter=
    +<demos/display_console/>

[env:demo_display_text]
build_src_filter=
    +<demos/display_text/>

[env:demo_display_graphics]
build_src_filter =
    +<demos/display_graphics/>

[env:demo_factory]
build_src_filter =
    +<demos/factory/>

[env:demo_png]
build_src_filter =
    +<demos/png/>

[env:demo_wifi]
build_src_filter =
    +<demos/wifi/>

[env:demo_rgb]
build_src_filter =
    +<demos/rgb/>
